### ISSUE TITLE
highlight regexp

### ISSUE THREAD

**Issue by KES777** [Blaizer/ModernPerl-sublime#30]
This code also highlighted incorrectly

```
    if( $dbg_call
    ) {
        BEGIN{ 'strict'->unimport( 'refs' )   if $options{ s } }
        # TODO: Here we may log internall subs call chain
        return &$DB::sub
    }
    ^---- text highlighted incorrectly until here 
```

here  `s } }` your false match for regex. Regexes in perl require no space after `s` and you, seems, allow spaces.

**Comment by Blaizer** [comment]
Are you sure no space is allowed after `s`?

**Comment by Blaizer** [comment]
`perl -E "say 'asd' =~ s }a}b}r"`

**Comment by Blaizer** [comment]
To clarify, I closed this issue because it's working as intended, as far as I know. I made it so that hash keys only get autoquoted inside `{ }` if there's no space on either or both sides of the word. This is so that you can do something like `sub { shift }`, and not have `shift` look like it's being autoquoted.

Doing autoquoting in a smarter way will probably be the better solution to this problem, rather than changing how `s///` works.
